interface IWord {
  id: string;
  group: number;
  page: number;
  word: string;
  image: string;
  audio: string;
  audioMeaning: string;
  audioExample: string;
  textMeaning: string;
  textExample: string;
  transcriptions: string;
  textExampleTranslate: string;
  textMeaningTranslate: string;
  wordTranslate: string;
}

export const data: Array<IWord> = [
  {
    id: '12',
    group: 0,
    page: 0,
    word: 'alcohol',
    image: 'files/01_0002.jpg',
    audio: 'files/01_0002.mp3',
    audioMeaning: 'files/01_0002_meaning.mp3',
    audioExample: 'files/01_0002_example.mp3',
    textMeaning: '<i>Alcohol</i> is a type of drink that can make people drunk.',
    textExample: 'A person should not drive a car after he or she has been drinking <b>alcohol</b>.',
    transcriptions: '[ǽlkəhɔ̀ːl]',
    textExampleTranslate: 'Человек не должен водить машину после того, как он выпил алкоголь',
    textMeaningTranslate: 'Алкоголь - это тип напитка, который может сделать людей пьяными',
    wordTranslate: 'алкоголь',
  },
  {

    id: '12',
    group: 0,
    page: 0,
    word: 'boat',
    image: 'files/01_0005.jpg',
    audio: 'files/01_0005.mp3',
    audioMeaning: 'files/01_0005_meaning.mp3',
    audioExample: 'files/01_0005_example.mp3',
    textMeaning: 'A <i>boat</i> is a vehicle that moves across water.',
    textExample: 'There is a small <b>boat</b> on the lake.',
    transcriptions: '[bout]',

    textExampleTranslate: 'На озере есть маленькая лодка',
    textMeaningTranslate: 'Лодка - это транспортное средство, которое движется по воде',
    wordTranslate: 'лодка',
  },
  {

    id: '12',
    group: 0,
    page: 0,
    word: 'agree',
    image: 'files/01_0001.jpg',
    audio: 'files/01_0001.mp3',
    audioMeaning: 'files/01_0001_meaning.mp3',
    audioExample: 'files/01_0001_example.mp3',
    textMeaning: 'To <i>agree</i> is to have the same opinion or belief as another person.',
    textExample: 'The students <b>agree</b> they have too much homework.',
    transcriptions: '[əgríː]',
    textExampleTranslate: 'Студенты согласны, что у них слишком много домашней работы',
    textMeaningTranslate: 'Согласиться - значит иметь то же мнение или убеждение, что и другой человек',
    wordTranslate: 'согласна',
  },
  {

    id: '12',
    group: 0,
    page: 0,
    word: 'arrive',
    image: 'files/01_0003.jpg',
    audio: 'files/01_0003.mp3',
    audioMeaning: 'files/01_0003_meaning.mp3',
    audioExample: 'files/01_0003_example.mp3',
    textMeaning: 'To <i>arrive</i> is to get somewhere.',
    textExample: 'They <b>arrived</b> at school at 7 a.m.',
    transcriptions: '[əráiv]',
    textExampleTranslate: 'Они прибыли в школу в 7 часов утра',
    textMeaningTranslate: 'Приехать значит попасть куда-то',
    wordTranslate: 'прибыть',
  },
  {

    id: '12',
    group: 0,
    page: 0,
    word: 'August',
    image: 'files/01_0004.jpg',
    audio: 'files/01_0004.mp3',
    audioMeaning: 'files/01_0004_meaning.mp3',
    audioExample: 'files/01_0004_example.mp3',
    textMeaning: '<i>August</i> is the eighth month of the year.',
    textExample: 'Is your birthday in <b>August</b>?',
    transcriptions: '[ɔ́ːgəst]',
    textExampleTranslate: 'У тебя день рождения в августе?',
    textMeaningTranslate: 'Август - восьмой месяц года',
    wordTranslate: 'август',
  },
  {

    id: '12',
    group: 0,
    page: 0,
    word: 'breakfast',
    image: 'files/01_0006.jpg',
    audio: 'files/01_0006.mp3',
    audioMeaning: 'files/01_0006_meaning.mp3',
    audioExample: 'files/01_0006_example.mp3',
    textMeaning: '<i>Breakfast</i> is the morning meal.',
    textExample: 'I ate eggs for <b>breakfast</b>.',
    transcriptions: '[brekfəst]',
    textExampleTranslate: 'Я ел яйца на завтрак',
    textMeaningTranslate: 'Завтрак - это утренняя трапеза',
    wordTranslate: 'завтрак',
  },
  {
    id: '12',
    group: 0,
    page: 0,
    word: 'camera',
    image: 'files/01_0007.jpg',
    audio: 'files/01_0007.mp3',
    audioMeaning: 'files/01_0007_meaning.mp3',
    audioExample: 'files/01_0007_example.mp3',
    textMeaning: 'A <i>camera</i> is a piece of equipment that takes pictures.',
    textExample: 'I brought my <b>camera</b> on my vacation.',
    transcriptions: '[kǽmərə]',
    textExampleTranslate: 'Я принес свою камеру в отпуск',
    textMeaningTranslate: 'Камера - это часть оборудования, которая делает снимки',
    wordTranslate: 'камера',
  },
  {

    id: '12',
    group: 0,
    page: 0,
    word: 'capital',
    image: 'files/01_0008.jpg',
    audio: 'files/01_0008.mp3',
    audioMeaning: 'files/01_0008_meaning.mp3',
    audioExample: 'files/01_0008_example.mp3',
    textMeaning: 'A <i>capital</i> is a city where a country’s government is based.',
    textExample: 'The <b>capital</b> of the United States is Washington, D.C.',
    transcriptions: '[kæpətl]',
    textExampleTranslate: 'Столица Соединенных Штатов - Вашингтон, округ Колумбия',
    textMeaningTranslate: 'Столица - это город, в котором базируется правительство страны',
    wordTranslate: 'столица',
  },
  {

    id: '12',
    group: 0,
    page: 0,
    word: 'catch',
    image: 'files/01_0009.jpg',
    audio: 'files/01_0009.mp3',
    audioMeaning: 'files/01_0009_meaning.mp3',
    audioExample: 'files/01_0009_example.mp3',
    textMeaning: 'To <i>catch</i> is to grab or get something.',
    textExample: 'Did you <b>catch</b> the ball during the baseball game?',
    transcriptions: '[kætʃ]',
    textExampleTranslate: 'Вы поймали мяч во время игры в бейсбол?',
    textMeaningTranslate: 'Поймать - значит схватить или получить что-то',
    wordTranslate: 'поймать',
  },
  {

    id: '12',
    group: 0,
    page: 0,
    word: 'duck',
    image: 'files/01_0010.jpg',
    audio: 'files/01_0010.mp3',
    audioMeaning: 'files/01_0010_meaning.mp3',
    audioExample: 'files/01_0010_example.mp3',
    textMeaning: 'A <i>duck</i> is a small water bird.',
    textExample: 'People feed <b>ducks</b> at the lake.',
    transcriptions: '[dʌk]',
    textExampleTranslate: 'Люди кормят уток у озера',
    textMeaningTranslate: 'Утка - маленькая водяная птица',
    wordTranslate: 'утка',
  },
  {

    id: '12',
    group: 0,
    page: 0,
    word: 'enjoy',
    image: 'files/01_0011.jpg',
    audio: 'files/01_0011.mp3',
    audioMeaning: 'files/01_0011_meaning.mp3',
    audioExample: 'files/01_0011_example.mp3',
    textMeaning: 'To <i>enjoy</i> is to like something.',
    textExample: 'The woman <b>enjoys</b> riding her bicycle.',
    transcriptions: '[indʒɔ́i]',
    textExampleTranslate: 'Женщина любит кататься на велосипеде',
    textMeaningTranslate: 'Наслаждаться значит любить что-то',
    wordTranslate: 'наслаждаться',
  },
  {

    id: '12',
    group: 0,
    page: 0,
    word: 'invite',
    image: 'files/01_0012.jpg',
    audio: 'files/01_0012.mp3',
    audioMeaning: 'files/01_0012_meaning.mp3',
    audioExample: 'files/01_0012_example.mp3',
    textMeaning: 'To <i>invite</i> is to ask someone to come to a place or event.',
    textExample: 'I will <b>invite</b> my friends to my birthday party.',
    transcriptions: '[inváit]',
    textExampleTranslate: 'Я приглашаю своих друзей на мой день рождения',
    textMeaningTranslate: 'Пригласить - это попросить кого-нибудь прийти на место или событие',
    wordTranslate: 'пригласить',
  },
  {

    id: '12',
    group: 0,
    page: 0,
    word: 'month',
    image: 'files/01_0014.jpg',
    audio: 'files/01_0014.mp3',
    audioMeaning: 'files/01_0014_meaning.mp3',
    audioExample: 'files/01_0014_example.mp3',
    textMeaning: 'A <i>month</i> is one of 12 periods of time in one year.',
    textExample: 'January is the first <b>month</b> of the year.',
    transcriptions: '[mʌnθ]',

    textExampleTranslate: 'январь - первый месяц года',
    textMeaningTranslate: 'Месяц - это один из 12 периодов времени в году',
    wordTranslate: 'месяц',
  },
  {

    id: '12',
    group: 0,
    page: 0,
    word: 'travel',
    image: 'files/01_0015.jpg',
    audio: 'files/01_0015.mp3',
    audioMeaning: 'files/01_0015_meaning.mp3',
    audioExample: 'files/01_0015_example.mp3',
    textMeaning: 'To <i>travel</i> is to go to a faraway place on vacation or business.',
    textExample: 'They will <b>travel</b> to Argentina this summer.',
    transcriptions: '[trǽvəl]',

    textExampleTranslate: 'Этим летом они отправятся в Аргентину',
    textMeaningTranslate: 'Путешествовать - это отправиться в далекое место на отдых или по делам',
    wordTranslate: 'путешествовать',
  },
  {

    id: '12',
    group: 0,
    page: 0,
    word: 'love',
    image: 'files/01_0013.jpg',
    audio: 'files/01_0013.mp3',
    audioMeaning: 'files/01_0013_meaning.mp3',
    audioExample: 'files/01_0013_example.mp3',
    textMeaning: 'To <i>love</i> is to like something or someone a lot.',
    textExample: 'I <b>love</b> my family very much.',
    transcriptions: '[lʌv]',

    textExampleTranslate: 'Я очень люблю свою семью',
    textMeaningTranslate: 'Любить значит любить что-то или кого-то много',
    wordTranslate: 'любовь',
  },
  {

    id: '12',
    group: 0,
    page: 0,
    word: 'typical',
    image: 'files/01_0016.jpg',
    audio: 'files/01_0016.mp3',
    audioMeaning: 'files/01_0016_meaning.mp3',
    audioExample: 'files/01_0016_example.mp3',
    textMeaning: 'If something is <i>typical</i>, it is normal, or something that usually happens.',
    textExample: 'My <b>typical</b> breakfast is toast and eggs.',
    transcriptions: '[típikəl]',

    textExampleTranslate: 'Мой типичный завтрак - тост и яйца',
    textMeaningTranslate: 'Если что-то типичное, это нормально, или что-то, что обычно происходит',
    wordTranslate: 'типичный',
  },
  {

    id: '12',
    group: 0,
    page: 0,
    word: 'visit',
    image: 'files/01_0017.jpg',
    audio: 'files/01_0017.mp3',
    audioMeaning: 'files/01_0017_meaning.mp3',
    audioExample: 'files/01_0017_example.mp3',
    textMeaning: 'To <i>visit</i> is to go and spend time in another place or see another person.',
    textExample: 'She wants to <b>visit</b> her grandmother.',
    transcriptions: '[vízit]',

    textExampleTranslate: 'Она хочет навестить свою бабушку',
    textMeaningTranslate: 'Посетить - значит пойти и провести время в другом месте или увидеть другого человека',
    wordTranslate: 'посещение',
  },
  {

    id: '12',
    group: 0,
    page: 0,
    word: 'weather',
    image: 'files/01_0018.jpg',
    audio: 'files/01_0018.mp3',
    audioMeaning: 'files/01_0018_meaning.mp3',
    audioExample: 'files/01_0018_example.mp3',
    textMeaning: '<i>Weather</i> is the temperature and the state of the outdoors.',
    textExample: 'Today’s <b>weather</b> is rainy and cloudy.',
    transcriptions: '[weðər]',

    textExampleTranslate: 'Сегодня погода дождливая и облачная',
    textMeaningTranslate: 'Погода это температура и состояние на улице',
    wordTranslate: 'погода',
  },
  {

    id: '12',
    group: 0,
    page: 0,
    word: 'wine',
    image: 'files/01_0020.jpg',
    audio: 'files/01_0020.mp3',
    audioMeaning: 'files/01_0020_meaning.mp3',
    audioExample: 'files/01_0020_example.mp3',
    textMeaning: '<i>Wine</i> is an alcoholic drink made from grapes.',
    textExample: 'The store carried both red and white <b>wine</b>.',
    transcriptions: '[wain]',

    textExampleTranslate: 'В магазине было красное и белое вино',
    textMeaningTranslate: 'Вино - это алкогольный напиток из винограда',
    wordTranslate: 'вино',
  },
  {

    id: '12',
    group: 0,
    page: 0,
    word: 'brother',
    image: 'files/01_0020.jpg',
    audio: 'files/01_0020.mp3',
    audioMeaning: 'files/01_0020_meaning.mp3',
    audioExample: 'files/01_0020_example.mp3',
    textMeaning: '<i>Wine</i> is an alcoholic drink made from grapes.',
    textExample: 'The store carried both red and white <b>wine</b>.',
    transcriptions: '[wain]',

    textExampleTranslate: 'В магазине было красное и белое вино',
    textMeaningTranslate: 'Вино - это алкогольный напиток из винограда',
    wordTranslate: 'брат',
  },
];
